http://data.ex.co.kr/openapi/basicinfo/openApiInfoM?apiId=0615&serviceType=&keyWord=&searchDayFrom=2014.12.01&searchDayTo=2022.05.30&CATEGORY=BU&GROUP_TR=

In [1]:
! pip install xmltodict

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Installing collected packages: xmltodict
Successfully installed xmltodict-0.13.0

In [2]:
import json

def parse_re(input_re: str):
    try:
        return_dict = json.loads(input_re)
    except json.decoder.JSONDecodeError:
        return_dict = dict()
    finally:
        return return_dict

In [3]:
import pandas as pd
from pandas.io.json import json_normalize
import requests
import pprint
import json

In [14]:
url = 'http://data.ex.co.kr/openapi/restinfo/hiwaySvarInfoList?key=test&type=json'
response = requests.get(url) 
contents = response.text 
json_ob = parse_re(contents)
body = json_ob['list']
dataframe = pd.DataFrame(body) # 전엔 빈 df 만들고 append 해줬었는데
                               # 그러지 않아도 쉽게 그냥.. 리스트를 그대로 데이터프레임 만들어주면 됨
                               # 기초가 중요하군!

In [15]:
dataframe

,routeCd,svarAddr,routeNm,svarCd,svarNm,hdqrCd,hdqrNm,mtnofCd,mtnofNm,svarGsstClssCd,svarGsstClssNm,gudClssCd,gudClssNm,pstnoCd,cocrPrkgTrcn,fscarPrkgTrcn,dspnPrkgTrcn,bsopAdtnlFcltCd,rprsTelNo
0,0010,경북 경주시 건천읍 경부고속도로 77,경부선,000485,건천(부산)주유소,600000,대구경북본부,610200,대구,1,주유소,1,하행,780900,0,0,0,B00200,0547514600
1,0010,경북 경주시 건천읍 방내리 14,경부선,000054,건천(부산)휴게소,600000,대구경북본부,610200,대구,0,휴게소,1,하행,780900,119,25,147,A00078,0547517810
2,0010,경북 경주시 건천읍 방내리 28-1,경부선,000053,건천(서울)주유소,600000,대구경북본부,610200,대구,1,주유소,0,상행,780900,0,0,0,B00053,0547518256
3,0010,경북 경주시 건천읍 금척리 683-2,경부선,000052,건천(서울)휴게소,600000,대구경북본부,610200,대구,0,휴게소,0,상행,780900,97,25,124,A00077,0547517401
4,0010,대구 북구 검단동 543-2 검단졸음쉼터,경부선,000453,검단졸음쉼터(부산),600000,대구경북본부,610200,대구,0,휴게소,1,하행,702801,0,0,0,None,0530000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,2510,충남 논산시 벌곡면 심양리 472-1,호남선의 지선,000241,벌곡(논산)주유소,800000,전북본부,810400,논산,1,주유소,1,하행,320880,0,0,0,B00032,0417337487
568,2510,충남 논산시 벌곡면 호남지선고속도로25,호남선의 지선,000240,벌곡(논산)휴게소,800000,전북본부,810400,논산,0,휴게소,1,하행,320880,79,57,140,A00043,0417327694
569,2510,충남 논산시 벌곡면 양산리 209,호남선의 지선,000239,벌곡(대전)주유소,800000,전북본부,810400,논산,1,주유소,0,상행,320883,0,0,0,B00105,0417323991
570,2510,충남 논산시 벌곡면 양산리124-1,호남선의 지선,000238,벌곡(대전)휴게소,800000,전북본부,810400,논산,0,휴게소,0,상행,320883,57,23,82,A00042,0417345250
571,2510,대전광역시 유성구 방현동 86 북대전IC(논산)졸음쉼터,호남선의 지선,000561,북대전(논산)졸음쉼터,400000,대전충남본부,410200,대전,0,휴게소,1,하행,30535,0,0,0,A00282,0420000000

In [16]:
dataframe.to_csv('expressway.csv',index=False)