<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#따로-구분-안지음" data-toc-modified-id="따로-구분-안지음-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>따로 구분 안지음</a></span></li><li><span><a href="#🤠" data-toc-modified-id="🤠-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>🤠</a></span></li><li><span><a href="#stnEnd,-stnEnd2-axis-=1" data-toc-modified-id="stnEnd,-stnEnd2-axis-=1-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>stnEnd, stnEnd2 axis =1</a></span></li><li><span><a href="#😺😺😺" data-toc-modified-id="😺😺😺-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>😺😺😺</a></span></li><li><span><a href="#df-테이블에-구간별-출발좌표,-도착좌표-colum-추가!-😺" data-toc-modified-id="df-테이블에-구간별-출발좌표,-도착좌표-colum-추가!-😺-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>df 테이블에 구간별 출발좌표, 도착좌표 colum 추가! 😺</a></span></li><li><span><a href="#str" data-toc-modified-id="str-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>str</a></span></li></ul></div>

In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set()
%matplotlib inline

In [86]:
df = pd.read_excel("real_newthing.xlsx")

In [87]:
df2 = pd.read_csv("stnEnd.csv")
df3 = pd.read_csv("stnEnd2.csv")

저번 전처리에서 나오지 않았던 동서울만남휴게소, 서여주(휴), 고속도로종점과 <br/>
다른 휴게소들도 상행, 하행 따로

## 따로 구분 안지음

In [ ]:
## 동서울만남휴게소 = 하남드림휴게소
## 상행 서여주(휴) = 서여주휴게소(양평방향)
## 하행 서여주(휴) = 서여주휴게소(창원방향)
## 고속도로종점 126.6175520764955, 37.43830063737166

In [164]:
a = """('127.2058613940864', '37.53045359533605')"""
b = """('127.5805530629789', '37.27872568138395')"""
c = """('126.6175520764955', '37.43830063737166')"""

In [165]:
구간명 = ['동서울만남휴게소','서여주(휴)','고속도로종점']
code= [a,b,c]
#Xcode,Ycode_x
#Xcode,Ycode_y = [('127.2058613940864','37.53045359533605'),('127.5805530629789','37.27872568138395'),('126.6175520764955','37.43830063737166')]

In [166]:
code

["('127.2058613940864', '37.53045359533605')",
 "('127.5805530629789', '37.27872568138395')",
 "('126.6175520764955', '37.43830063737166')"]

In [167]:
t1 = pd.DataFrame(data=code)

In [168]:
t2 = pd.DataFrame(data=구간명)
t2 = t2.rename(columns={0:'name'})

In [169]:
t2

       name
0  동서울만남휴게소
1    서여주(휴)
2    고속도로종점

In [170]:
NT = pd.concat([t1,t2],axis=1) # axis=1 옆으로 이어붙임
NT = NT.rename(columns={0:'Xcode,Ycode'})
NT

                                  Xcode,Ycode      name
0  ('127.2058613940864', '37.53045359533605')  동서울만남휴게소
1  ('127.5805530629789', '37.27872568138395')    서여주(휴)
2  ('126.6175520764955', '37.43830063737166')    고속도로종점

In [41]:
df # 월 -> 구간명 정렬

,월,구간명,주간평균속도(km/h),전일평균속도(km/h),사고횟수,사고지점위도,사고지점경도
0,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000
1,1,88JC ~ 북로JC,91.727273,90.666667,0,0.000000,0.000000
2,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.215920,127.601973
3,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.226046,127.592447
4,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.219362,127.596975
...,...,...,...,...,...,...,...
8338,12,화성휴게소 ~ 비봉IC,81.161290,86.354839,4,37.238843,126.881435
8339,12,흥덕IC ~ 광교상현IC,76.129032,82.903226,0,0.000000,0.000000
8340,12,흥천이포IC ~ 대신IC,98.580645,99.387097,1,37.381158,127.552524
8341,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.377812,127.477180
8342,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251

## 🤠

In [76]:
df.sort_values(by=['구간명']) # 구간명 별 정렬

,월,구간명,주간평균속도(km/h),전일평균속도(km/h),사고횟수,사고지점위도,사고지점경도
0,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000
2038,4,88JC ~ 김포공항IC,95.666667,95.433333,0,0.000000,0.000000
2746,5,88JC ~ 김포공항IC,94.838710,94.935484,0,0.000000,0.000000
3474,6,88JC ~ 김포공항IC,95.700000,95.866667,0,0.000000,0.000000
4219,7,88JC ~ 김포공항IC,95.354839,95.161290,0,0.000000,0.000000
...,...,...,...,...,...,...,...
2745,4,흥천이포IC ~ 동곤지암IC,85.233333,86.033333,0,0.000000,0.000000
2037,3,흥천이포IC ~ 동곤지암IC,88.935484,91.612903,0,0.000000,0.000000
1359,2,흥천이포IC ~ 동곤지암IC,85.777778,87.500000,0,0.000000,0.000000
4218,6,흥천이포IC ~ 동곤지암IC,83.333333,84.400000,0,0.000000,0.000000
8342,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251

## stnEnd, stnEnd2 axis =1

In [158]:
df2

     Unnamed: 0                               Xcode,Ycode    name
0             0  ('126.820343344967', '37.5840623931627')    88JC
1             1  ('127.670103878549', '37.1245612761955')    감곡IC
2             2  ('127.165506102561', '37.5729828463899')    강일IC
3             3  ('127.624573514836', '37.7346229537189')    강촌IC
4             4  ('126.618394195987', '37.6006109294591')  검단양촌IC
..          ...                                       ...     ...
204         204  ('127.427164981905', '37.2350583920676')    호법JC
205         205  ('127.311299808984', '37.6318075886669')    화도IC
206         206   ('126.87914101492', '37.1435857940843')   화성휴게소
207         207  ('127.079345318541', '37.2786918516755')    흥덕IC
208         208  ('127.515792793563', '37.3784480059131')  흥천이포IC

[209 rows x 3 columns]

In [182]:
df5 = pd.concat([df2,df3,NT])
df5
df5 = df5.drop(labels='Unnamed: 0',axis=1)
df5 = df5.reset_index(drop=True)

df5 = df5.rename(columns={'name':'str'})
df5

                                    Xcode,Ycode       str
0      ('126.820343344967', '37.5840623931627')      88JC
1      ('127.670103878549', '37.1245612761955')      감곡IC
2      ('127.165506102561', '37.5729828463899')      강일IC
3      ('127.624573514836', '37.7346229537189')      강촌IC
4      ('126.618394195987', '37.6006109294591')    검단양촌IC
..                                          ...       ...
416     ('127.217046957023', '37.914081203383')      신북IC
417    ('127.016056291369', '37.5097538823881')      잠원IC
418  ('127.2058613940864', '37.53045359533605')  동서울만남휴게소
419  ('127.5805530629789', '37.27872568138395')    서여주(휴)
420  ('126.6175520764955', '37.43830063737166')    고속도로종점

[421 rows x 2 columns]

없었던 동서울만남휴게소, 서여주(휴), 고속도로종점도 이어붙였다!

## 😺😺😺

In [92]:
df5.dtypes

Xcode,Ycode    object
str            object
dtype: object

df5 = df5[~df5['str'].str.contains('휴게소')]
df5 = df5.reset_index(drop=True)
df5

## df 테이블에 구간별 출발좌표, 도착좌표 colum 추가! 😺

In [172]:
df.head(3)

   월            구간명  주간평균속도(km/h)  전일평균속도(km/h)  사고횟수    사고지점위도      사고지점경도
0  1  88JC ~ 김포공항IC     93.129032     93.419355     0   0.00000    0.000000
1  1    88JC ~ 북로JC     91.727273     90.666667     0   0.00000    0.000000
2  1    감곡IC ~ 여주JC     99.000000     96.612903     6  37.21592  127.601973

In [180]:
df['str'] = df.구간명.str.split(' ~ ').str[0]
df['end'] = df.구간명.str.split(' ~ ').str[1]
df

,월,구간명,주간평균속도(km/h),전일평균속도(km/h),사고횟수,사고지점위도,사고지점경도,str,end
0,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC
1,1,88JC ~ 북로JC,91.727273,90.666667,0,0.000000,0.000000,88JC,북로JC
2,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.215920,127.601973,감곡IC,여주JC
3,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.226046,127.592447,감곡IC,여주JC
4,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.219362,127.596975,감곡IC,여주JC
...,...,...,...,...,...,...,...,...,...
8338,12,화성휴게소 ~ 비봉IC,81.161290,86.354839,4,37.238843,126.881435,화성휴게소,비봉IC
8339,12,흥덕IC ~ 광교상현IC,76.129032,82.903226,0,0.000000,0.000000,흥덕IC,광교상현IC
8340,12,흥천이포IC ~ 대신IC,98.580645,99.387097,1,37.381158,127.552524,흥천이포IC,대신IC
8341,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.377812,127.477180,흥천이포IC,동곤지암IC
8342,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC

## str

In [183]:
result = pd.merge(left=df,right=df5,how='left',on='str')
result

,월,구간명,주간평균속도(km/h),전일평균속도(km/h),사고횟수,사고지점위도,사고지점경도,str,end,"Xcode,Ycode"
0,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC,"('126.820343344967', '37.5840623931627')"
1,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC,"('126.820343344967', '37.5840623931627')"
2,1,88JC ~ 북로JC,91.727273,90.666667,0,0.000000,0.000000,88JC,북로JC,"('126.820343344967', '37.5840623931627')"
3,1,88JC ~ 북로JC,91.727273,90.666667,0,0.000000,0.000000,88JC,북로JC,"('126.820343344967', '37.5840623931627')"
4,1,감곡IC ~ 여주JC,99.000000,96.612903,6,37.215920,127.601973,감곡IC,여주JC,"('127.670103878549', '37.1245612761955')"
...,...,...,...,...,...,...,...,...,...,...
16633,12,흥천이포IC ~ 대신IC,98.580645,99.387097,1,37.381158,127.552524,흥천이포IC,대신IC,"('127.515792793563', '37.3784480059131')"
16634,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.377812,127.477180,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')"
16635,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.377812,127.477180,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')"
16636,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')"
16637,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')"

In [184]:
df5 = df5.rename(columns={'str':'end'})
df5

                                    Xcode,Ycode       end
0      ('126.820343344967', '37.5840623931627')      88JC
1      ('127.670103878549', '37.1245612761955')      감곡IC
2      ('127.165506102561', '37.5729828463899')      강일IC
3      ('127.624573514836', '37.7346229537189')      강촌IC
4      ('126.618394195987', '37.6006109294591')    검단양촌IC
..                                          ...       ...
416     ('127.217046957023', '37.914081203383')      신북IC
417    ('127.016056291369', '37.5097538823881')      잠원IC
418  ('127.2058613940864', '37.53045359533605')  동서울만남휴게소
419  ('127.5805530629789', '37.27872568138395')    서여주(휴)
420  ('126.6175520764955', '37.43830063737166')    고속도로종점

[421 rows x 2 columns]

In [185]:
result2 = pd.merge(left=result,right=df5,how='left',on='end')
result2

,월,구간명,주간평균속도(km/h),전일평균속도(km/h),사고횟수,사고지점위도,사고지점경도,str,end,"Xcode,Ycode_x","Xcode,Ycode_y"
0,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC,"('126.820343344967', '37.5840623931627')","('126.791097867713', '37.583844872726')"
1,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC,"('126.820343344967', '37.5840623931627')","('126.791097867713', '37.583844872726')"
2,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC,"('126.820343344967', '37.5840623931627')","('126.791097867713', '37.583844872726')"
3,1,88JC ~ 김포공항IC,93.129032,93.419355,0,0.000000,0.000000,88JC,김포공항IC,"('126.820343344967', '37.5840623931627')","('126.791097867713', '37.583844872726')"
4,1,88JC ~ 북로JC,91.727273,90.666667,0,0.000000,0.000000,88JC,북로JC,"('126.820343344967', '37.5840623931627')","('126.833256331126', '37.5954482478014')"
...,...,...,...,...,...,...,...,...,...,...,...
33175,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.377812,127.477180,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')","('127.400659883125', '37.3808979664337')"
33176,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')","('127.400659883125', '37.3808979664337')"
33177,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')","('127.400659883125', '37.3808979664337')"
33178,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')","('127.400659883125', '37.3808979664337')"
33179,12,흥천이포IC ~ 동곤지암IC,86.483871,90.483871,2,37.379723,127.413251,흥천이포IC,동곤지암IC,"('127.515792793563', '37.3784480059131')","('127.400659883125', '37.3808979664337')"

In [186]:
result2.isnull().sum()

월                0
구간명              0
주간평균속도(km/h)     0
전일평균속도(km/h)     0
사고횟수             0
사고지점위도           0
사고지점경도           0
str              0
end              0
Xcode,Ycode_x    0
Xcode,Ycode_y    0
dtype: int64

In [187]:
result2.to_csv('result2.csv')